development: &default
  adapter: postgresql
  encoding: unicode
  database: partaker
  pool: 5
  username: partaker
  password: 42
  host: localhost

test:
  <<: *default
  database: acessoajustica_test
